### ISSUE TITLE
Validation error on manual input in the SPA

### ISSUE THREAD

**Issue by AliciaMstt** [Zendro-dev/single-page-app#13]
I manually created a new entry in the Accessions model and on purpose wrote a character string in a field requesting an integer. The system does not highlight the error, but when I tried to save it gave the error of the screenshot below. I think this error would be too cryptic to an user. Also notice the thickmarks (palomitas) in the offending fields, which would make it even harder to notice that these fields are what is wrong, even if they have a nice tickmark.

We need to specifically highlight that an integer was expected and that the user wrote text. Or even better, only to allow integers to be typedin the field (I have seen this done elsewhere).

![image](https://user-images.githubusercontent.com/5412404/73370810-6bc90180-427a-11ea-8622-b0b3090b2729.png)

**Comment by framirez07** [comment]
Improvements made on the Int and Float fields.

**Commit:**
[spa-codegen](https://github.com/ScienceDb/single-page-app-codegen/commit/46e6da87967eddbc212a0d96339bf0536d7f3692)

**Comment by framirez07** [comment]
Already [fixed](https://github.com/Zendro-dev/single-page-app-codegen/releases/tag/0.1.5).
