### ISSUE TITLE
Add detailed build instructions especially explaining how to set the environment variables correctly

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/single-page-app#16]
When I build the production version of the single page application, how do I need to define the environment variables like REACT_APP_CENZ_GRAPHQL_SERVER_URL so that they are correctly set in the compiled SPA? Please add this to the skeleton server README!

**Comment by davelsan** [comment]
This has been addressed in the `develop` branch (new frontend) in the following commits:
- 8935c025c7129567d6563134c108d58636d5ce45 - added an `.env.development` file with some defaults and instructions on how to configure it for production.
- 04c8c51d457c7aa8ea8bbca6df47205d20655335 - added the documentation for NEXT environment variables.

In the GraphQL server, this has also been added in the following PR:
- https://github.com/Zendro-dev/graphql-server/pull/66 - made critical variables mandatory and documented how to configure an `.env`.
