### ISSUE TITLE
Fix new branch vue-cli-3

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/single-page-app#7]
Because the current version of single-page-app does not work when built and statically served, it was decided to switch to the latest version of [vue-cli](https://cli.vuejs.org/guide/).

A new Vue project was created with `vue create` and then the files from the latest version of `single-page-app` master branch were `rsync`ed with the new project.

Paths to Javascript libraries and stylesheets were adjusted with `<%= BASE_URL %>` in `public/index.html`, see the [oficial manual](https://cli.vuejs.org/guide/html-and-static-assets.html#the-public-folder) for more details on the latest way of handling static content and assets.

The problem is that when serving (`npm run serve`) the vue-cli-3 version of the single-page-app the navigation and login components are not rendered and are not shown in the browser.

The code to fix is stored in the [`vue-cli-3` branch](https://github.com/ScienceDb/single-page-app/tree/vue-cli-3) of this project.

### Expected work time: 4h

**Comment by davelsan** [comment]
Closing this issue. It is no longer applicable to the current SPA.
